from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

from kinetic.models.inputs import CheckInPayload
from kinetic.models.outputs import BehavioralProfile, BehavioralSummary


@runtime_checkable
class DatabaseClient(Protocol):
    async def insert_checkin(
        self, payload: CheckInPayload, message: str, liaison_feedback: str | None = None
    ) -> str: ...

    async def get_latest_bio(self) -> dict[str, Any] | None: ...

    async def get_all_tasks(self) -> list[dict[str, Any]]: ...

    async def get_all_vibes(self) -> list[dict[str, Any]]: ...

    async def get_recent_bio(self, limit: int = 7) -> list[dict[str, Any]]: ...

    async def upsert_contact_pause(
        self, person: str, paused_until: str, reason: str | None
    ) -> None: ...

    async def get_active_pauses(self) -> list[dict[str, Any]]: ...

    async def get_history(self, limit: int = 20) -> list[dict[str, str]]: ...

    async def get_behavioral_summary(self, days: int = 14) -> BehavioralSummary: ...

    async def get_behavioral_profiles(self) -> list[BehavioralProfile]: ...

    async def upsert_behavioral_profile(self, profile: BehavioralProfile) -> None: ...

    async def complete_task(self, task_name: str) -> None: ...

    async def clear_database(self) -> None: ...
